### ISSUE TITLE
Rails crash

### ISSUE THREAD

**Issue by gamecompiler** [Terasology/Rails#3]
Hi, id fetched the current Terasology development Branch today and also the stable Branch.
And id decided to load the Rails module.
But i always get a instant crash while loading a world.
My Crash logs are attached.

Maybe you can help me.
Thanks in advance :)

[Terasology-init.log.txt](https://github.com/Terasology/Rails/files/129358/Terasology-init.log.txt)
[Terasology-menu.log.txt](https://github.com/Terasology/Rails/files/129360/Terasology-menu.log.txt)
[Terasology-Game_1.log.txt](https://github.com/Terasology/Rails/files/129359/Terasology-Game_1.log.txt)

**Comment by Cervator** [comment]
Hi @gamecompiler :-)

Rails is currently broken, we know :( That's why it isn't in the stable module lineup at the moment.

@SkySom tried to fix it up and got just about everything working, but then got stuck on a last bit. Unless he has made progress since last anyway - ping!

I know he dug up a bunch of details, we talked about it somewhere. May only have been on IRC though.

**Comment by SkySom** [comment]
Haven't had time recently to continue attempting it. And yeah the discussion was only on irc.

**Comment by SkySom** [comment]
So rails no longer crashes. There are a few other issues with it, but it at least doesn't kill everything any more.
